source "${HOME}/.config/zsh/common/nix.zsh"
source "${HOME}/.config/zsh/common/aliases.zsh"
source "${HOME}/.config/zsh/common/mise.zsh"
source "${HOME}/.config/zsh/common/starship.zsh"
source "${HOME}/.config/zsh/common/zoxide.zsh"
source "${HOME}/.config/zsh/common/fzf.zsh"
